Update pipelineIC.yml

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -20,7 +20,6 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: "if [ -f \"build.gradle\" ]; then\n  echo \"Encontró el archivo\"\n  echo \"Verificando configuracion del plugin sonar\"\n  if ! grep -q  'id \"org.sonarqube\" version \"3.3\"' build.gradle; then\n    echo \"No se encuentra Plugin configurado\"\n    sed -i '/id '\\''java'\\''/a \\ \\ \\ \\ id '\\''org.sonarqube'\\'' version '\\''3.3'\\''' build.gradle\n    echo \"Plugin de Sonarcloud acaba de ser añadido a build.gradle\"\n    cat build.gradle\n  else \n    echo \"Plugin de sonarcloud ya está configurado en build.gradle\"\n  fi\n\n\nelse\n  echo \"no se encontró archivo build.gradle\"\n  exit 1\nfi\n"
-      # - name: Validando existencia de proyecto en SonarCloud
       #   id: validateProjectOnSonar
       #   run: |
       #     #pwd
@@ -40,6 +39,8 @@ jobs:
       #     #fi
       #     #set -e
       - name: Validate or Create SonarCloud Project
+        # - name: Validando existencia de proyecto en SonarCloud
+
         id: validate-project
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -58,15 +59,25 @@ jobs:
               -d "organization=glemos-as" \
               -d "visibility=public")
 
-            if [ "$create_response" -ne 201 ]; then
-              echo "¨Proyecto creado exitosamente (HTTP $create_response)."
+            if [ "$create_response" -eq 201 ]; then
+              echo "Proyecto creado exitosamente (HTTP $create_response)."
+            else
+              echo "Error al crear el proyecto (HTTP $create_response)."
+              exit 1
             fi
 
             echo "Estableciendo la rama main como predeterminada..."
-            curl -s -f -X POST -u "$SONAR_TOKEN:" \
+            branch_response=$(curl -s -w "%{http_code}" -o /dev/null -X POST -u "$SONAR_TOKEN:" \
               "https://sonarcloud.io/api/project_branches/rename" \
               -d "name=main" \
-              -d "project=$REPO_NAME"
+              -d "project=$REPO_NAME")
+
+            if [ "$branch_response" -eq 200 ]; then
+              echo "Rama main establecida como predeterminada (HTTP $branch_response)."
+            else
+              echo "Error al establecer la rama main (HTTP $branch_response)."
+              exit 1
+            fi
 
             echo "project_created=true" >> $GITHUB_ENV
           else
