Update pipelineIC.yml

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -1,8 +1,10 @@
 name: Workflow
+
 on:
   push:
     branches:
       - feature-clase1
+
 jobs:
   SAST:
     runs-on: ubuntu-24.04
@@ -24,33 +26,57 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
           if [ -f "build.gradle" ]; then
-            echo "Encontró el archivo"
-            echo "Verificando configuración del plugin sonar"
-            if ! grep -q  'id "org.sonarqube" version "3.3"' build.gradle; then
-              echo "No se encuentra Plugin configurado"
+            echo "Archivo build.gradle encontrado"
+            echo "Verificando configuración del plugin de SonarCloud"
+
+            # Verifica si el plugin de SonarCloud ya está configurado
+            if ! grep -q 'id "org.sonarqube" version "3.3"' build.gradle; then
+              echo "Plugin de SonarCloud no configurado. Añadiendo al archivo build.gradle..."
               sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
-              echo "Plugin de Sonarcloud acaba de ser añadido a build.gradle"
-              cat build.gradle
-            else 
-              echo "Plugin de Sonarcloud ya está configurado en build.gradle"
+              echo "Plugin de SonarCloud añadido con éxito"
+            else
+              echo "Plugin de SonarCloud ya está configurado en build.gradle"
             fi
+
+            cat build.gradle
           else
             echo "No se encontró archivo build.gradle"
             exit 1
           fi
 
-      - name: Validando existencia de proyecto en SonarCloud
+      - name: Validate Project in SonarCloud
         id: validateProjectOnSonar
         run: |
-          # echo "Siguiente"
-          curl -v -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/projects/create" -d "name=pet-clinic" -d "project=pet-clinic" -d "organization=glemosas" -d "visibility=public"
-          if [ $? -ne 0 ]; then
+          PROJECT_NAME="pet-clinic-prueba"
+          ORGANIZATION="glemosas"
+          
+          # Intenta crear el proyecto en SonarCloud
+          echo "Verificando si el proyecto ya existe en SonarCloud..."
+
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+            "https://sonarcloud.io/api/projects/create" \
+            -d "name=${PROJECT_NAME}" \
+            -d "project=${PROJECT_NAME}" \
+            -d "organization=${ORGANIZATION}" \
+            -d "visibility=public")
+
+          if [ "$response" -eq 400 ]; then
+            echo "Proyecto '${PROJECT_NAME}' ya existe en SonarCloud"
             echo "project_created=false" >> $GITHUB_ENV
-          else
-            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
-            echo "Se establece rama main como rama por defecto"
-            curl -v -f -X POST -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/project_branches/rename" -d "name=main" -d "project=${{ github.event.repository.name }}"
+          elif [ "$response" -eq 200 ]; then
+            echo "Proyecto '${PROJECT_NAME}' creado exitosamente en SonarCloud"
+            echo "Se establece la rama 'main' como rama por defecto"
+            
+            # Cambia la rama principal a 'main'
+            curl -s -o /dev/null -w "%{http_code}" -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+              "https://sonarcloud.io/api/project_branches/rename" \
+              -d "name=main" \
+              -d "project=${PROJECT_NAME}"
+            
             echo "project_created=true" >> $GITHUB_ENV
+          else
+            echo "Error al crear el proyecto en SonarCloud. Código de respuesta: $response"
+            exit 1
           fi
 
 
