Update pipelineIC.yml

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -1,186 +1,142 @@
-# name: Workflow
-# on:
-#   push:
-#     branches:
-#       - main
+name: Workflow
 
-# jobs:
-#   SAST:
-#     runs-on: ubuntu-24.04
+on:
+  push:
+    branches:
+      - main
 
-#     steps:
-#       - name: Checkout Code
-#         uses: actions/checkout@v3
-      
-#       - name: Set up JDK 17
-#         uses: actions/setup-java@v2
-#         with:
-#           java-version: '17'
-#           distribution: 'adopt'
-      
-#       - name: Set Environment Variables
-#         run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
+jobs:
+  SAST:
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
-#       - name: Validate and Configure build.gradle
-#         env: 
-#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#         run: |
-#           if [ -f "build.gradle" ]; then
-#             echo "Encontró el archivo"
-#             echo "Verificando configuracion del plugin sonar"
-#             if ! grep -q  'id "org.sonarqube" version "3.3"' build.gradle; then
-#               echo "No se encuentra Plugin configurado"
-#               sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
-#               echo "Plugin de Sonarcloud acaba de ser añadido a build.gradle"
-#               cat build.gradle
-#             else 
-#               echo "Plugin de sonarcloud ya está configurado en build.gradle"
-#             fi
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          java-version: '17'
+          distribution: 'adopt'
 
+      - name: Set Environment Variables
+        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
 
-#           else
-#             echo "no se encontró archivo build.gradle"
-#             exit 1
-#           fi
+      - name: Validate and Configure build.gradle
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          if [ -f "build.gradle" ]; then
+            echo "Archivo build.gradle encontrado"
+            echo "Verificando configuración del plugin de SonarCloud"
 
+            # Verifica si el plugin de SonarCloud ya está configurado
+            if ! grep -q 'id "org.sonarqube" version "3.3"' build.gradle; then
+              echo "Plugin de SonarCloud no configurado. Añadiendo al archivo build.gradle..."
+              sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
+              echo "Plugin de SonarCloud añadido con éxito"
+            else
+              echo "Plugin de SonarCloud ya está configurado en build.gradle"
+            fi
 
-#       - name: Validando existencia de proyecto en SonarCloud
-#         id: validateProjectOnSonar
-#         run: |
-#           #pwd
-#           #ls -R
-#           set +e
-#           curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=devsecopsusach' -d 'visibility=public'
-#           if [ $? -ne 0 ]; then
-#             echo "Proyecto ya existe en Sonarcloud"
-#             echo "project_created=false" >> $GITHUB_ENV
-#           else
-#             echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
+            cat build.gradle
+          else
+            echo "No se encontró archivo build.gradle"
+            exit 1
+          fi
+
+      - name: Validate Project in SonarCloud
+        id: validateProjectOnSonar
+        run: |
+          PROJECT_NAME="pet-clinic-prueba"
+          ORGANIZATION="glemosas"
+          
+          # Intenta crear el proyecto en SonarCloud
+          echo "Verificando si el proyecto ya existe en SonarCloud..."
+
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+            "https://sonarcloud.io/api/projects/create" \
+            -d "name=${PROJECT_NAME}" \
+            -d "project=${PROJECT_NAME}" \
+            -d "organization=${ORGANIZATION}" \
+            -d "visibility=public")
+
+          if [ "$response" -eq 400 ]; then
+            echo "Proyecto '${PROJECT_NAME}' ya existe en SonarCloud"
+            echo "project_created=false" >> $GITHUB_ENV
+          elif [ "$response" -eq 200 ]; then
+            echo "Proyecto '${PROJECT_NAME}' creado exitosamente en SonarCloud"
+            echo "Se establece la rama 'main' como rama por defecto"
             
-#             echo "Se establece rama main como rama por defecto"
-#             curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
-#             echo "project_created=true" >> $GITHUB_ENV
-#           fi
-#           set -e
-      
-#       # name: Validate or Create SonarCloud Project
-#       # id: validate-project
-#       # env:
-#       #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#       #   REPO_NAME: ${{ github.event.repository.name }}
-#       # run: |
-#       #   echo "Verificando si el proyecto $REPO_NAME existe en SonarCloud..."
-#       #   response=$(curl -s -o /dev/null -w "%{http_code}" -u "$SONAR_TOKEN:" \
-#       #     "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME")
+            # Cambia la rama principal a 'main'
+            curl -s -o /dev/null -w "%{http_code}" -X POST -u "${{ secrets.SONAR_TOKEN }}:" \
+              "https://sonarcloud.io/api/project_branches/rename" \
+              -d "name=main" \
+              -d "project=${PROJECT_NAME}"
+            
+            echo "project_created=true" >> $GITHUB_ENV
+          else
+            echo "Error al crear el proyecto en SonarCloud. Código de respuesta: $response"
+            exit 1
+          fi
 
-#       #   if [ "$response" -ne 200 ]; then
-#       #     echo "El proyecto no existe. Creándolo en SonarCloud..."
-#       #     create_response=$(curl -s -w "%{http_code}" -o /dev/null -X POST -u "$SONAR_TOKEN:" \
-#       #       "https://sonarcloud.io/api/projects/create" \
-#       #       -d "name=$REPO_NAME" \
-#       #       -d "project=$REPO_NAME" \
-#       #       -d "organization=devsecopsusach" \
-#       #       -d "visibility=public")
 
-#       #     if [ "$create_response" -ne 201 ]; then
-#       #       echo "¨Proyecto creado exitosamente (HTTP $create_response)."
-#       #     fi
+      - name: Enable execution gradlew
+        run: |
+          chmod +x gradlew
 
-#       #     echo "Estableciendo la rama main como predeterminada..."
-#       #     curl -s -f -X POST -u "$SONAR_TOKEN:" \
-#       #       "https://sonarcloud.io/api/project_branches/rename" \
-#       #       -d "name=main" \
-#       #       -d "project=$REPO_NAME"
+      - name: Perform Initial Analysis (if Project Created)
+        if: env.project_created == 'true'
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          REPO_NAME: pet-clinic-prueba
+        run: |
+          echo "Realizando análisis inicial en la rama main..."
+          ./gradlew sonarqube \
+            -Dsonar.projectKey=$REPO_NAME \
+            -Dsonar.organization=glemosas \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.token=$SONAR_TOKEN \
+            -Dsonar.branch.name=main
 
-#       #     echo "project_created=true" >> $GITHUB_ENV
-#       #   else
-#       #     echo "El proyecto ya existe en SonarCloud."
-#       #     echo "project_created=false" >> $GITHUB_ENV
-#       #   fi
+      - name: Perform Branch Analysis
+        if: env.project_created == 'false'
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          REPO_NAME: pet-clinic-prueba
+          BRANCH_NAME: ${{ github.ref_name }}
+        run: |
+          echo "Realizando análisis en la rama actual: $BRANCH_NAME..."
+          ./gradlew sonarqube \
+            -Dsonar.projectKey=$REPO_NAME \
+            -Dsonar.organization=glemosas \
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.token=$SONAR_TOKEN \
+            -Dsonar.branch.name=${{ github.ref_name }}
 
-#       - name: Enable execution gradlew
-#         run: | 
-#           chmod 777 gradlew
+      - name: Validate Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          REPO_NAME: pet-clinic-prueba
+        run: |
+          echo "Validando el estado del Quality Gate..."
+          analysisId=$(curl -s -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')
 
-#       - name: Perform Initial Analysis (if Project Created)
-#         if: env.project_created == 'true'
-#         env:
-#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#           REPO_NAME: ${{ github.event.repository.name }}
-#         run: |
-#           echo "Realizando análisis inicial en la rama main..."
-#           ./gradlew sonarqube \
-#             -Dsonar.projectKey=$REPO_NAME \
-#             -Dsonar.organization=devsecopsusach \
-#             -Dsonar.host.url=https://sonarcloud.io \
-#             -Dsonar.token=$SONAR_TOKEN \
-#             -Dsonar.branch.name=main
+          if [ -z "$analysisId" ]; then
+            echo "No se encontró un análisis reciente. Verifique la configuración."
+            exit 1
+          fi
 
-#       - name: Perform Branch Analysis
-#         if: env.project_created == 'false'
-#         env:
-#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#           REPO_NAME: ${{ github.event.repository.name }}
-#           BRANCH_NAME: ${{ github.ref_name }}
-#         run: |
-#           echo "Realizando análisis en la rama actual: $BRANCH_NAME..."
-#           ./gradlew sonarqube \
-#             -Dsonar.projectKey=$REPO_NAME \
-#             -Dsonar.organization=devsecopsusach \
-#             -Dsonar.host.url=https://sonarcloud.io \
-#             -Dsonar.token=$SONAR_TOKEN \
-#             -Dsonar.branch.name=$BRANCH_NAME
+          qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
 
-#       - name: Validate Quality Gate
-#         env:
-#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#           REPO_NAME: ${{ github.event.repository.name }}
-#         run: |
-#           echo "Validando el estado del Quality Gate..."
-#           analysisId=$(curl -s -u "$SONAR_TOKEN:" \
-#             "https://sonarcloud.io/api/ce/component?component=$REPO_NAME" | jq -r '.current.analysisId')
+          if [ "$qualityGateStatus" != "OK" ]; then
+            echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus."
+            echo "Verificando vulnerabilidades críticas..."
+            vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')
 
-#           qualityGateStatus=$(curl -s -u "$SONAR_TOKEN:" \
-#             "https://sonarcloud.io/api/qualitygates/project_status?analysisId=$analysisId" | jq -r '.projectStatus.status')
-
-#           if [ "$qualityGateStatus" != "OK" ]; then
-#             echo "El proyecto no cumple con el Quality Gate: $qualityGateStatus."
-#             echo "Verificando vulnerabilidades críticas..."
-#             vulnerabilities=$(curl -s -u "$SONAR_TOKEN:" \
-#               "https://sonarcloud.io/api/issues/search?componentKeys=$REPO_NAME&types=VULNERABILITY&severities=CRITICAL,BLOCKER" | jq -r '.total')
-
-#             if [ "$vulnerabilities" -gt 0 ]; then
-#               echo "Se encontraron $vulnerabilities vulnerabilidades críticas. El proyecto no cumple con los estándares de seguridad."
-#               #exit 1
-#             fi
-#           else
-#             echo "El proyecto cumple con el Quality Gate y no tiene vulnerabilidades críticas. Continuando sin problemas."
-#           fi
-
-#   SCA:
-#     needs: SAST
-#     runs-on: ubuntu-24.04
-#     steps:
-    
-#     - name: Checkout code
-#       uses: actions/checkout@v2
-    
-#     - name: Dependency Check
-#       uses: dependency-check/Dependency-Check_Action@1.1.0
-#       env:
-#         JAVA_HOME: /opt/jdk
-#       id: Depcheck
-#       with:
-#         project: '${{ github.event.repository.name }}'
-#         path: '.'
-#         format: 'HTML'
-#         args: >
-#           --out ./reports
-#           --failOnCVSS 7
-#           --enableRetired
-
-#     - name: Upload Test Result
-#       uses: actions/upload-artifact@master
-#       with:
-#         name: Depcheck Report
-#         path: ./reports
+            if [ "$vulnerabilities" -gt 0 ]; then
+              echo "Se encontraron $vulnerabilities vulnerabilidades críticas. El proyecto no cumple con los estándares de seguridad."
+              exit 1
+            fi
+          else
+            echo "El proyecto cumple con el Quality Gate y no tiene vulnerabilidades críticas. Continuando sin problemas."
+          fi
