Update pipelineIC.yml

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -3,105 +3,79 @@ on:
   push:
     branches:
       - feature-clase1
-
 jobs:
   SAST:
     runs-on: ubuntu-24.04
-
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
-      
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
           java-version: '17'
           distribution: 'adopt'
-      
       - name: Set Environment Variables
         run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
-
       - name: Validate and Configure build.gradle
-        env: 
+        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: "if [ -f \"build.gradle\" ]; then\n  echo \"Encontró el archivo\"\n  echo \"Verificando configuracion del plugin sonar\"\n  if ! grep -q  'id \"org.sonarqube\" version \"3.3\"' build.gradle; then\n    echo \"No se encuentra Plugin configurado\"\n    sed -i '/id '\\''java'\\''/a \\ \\ \\ \\ id '\\''org.sonarqube'\\'' version '\\''3.3'\\''' build.gradle\n    echo \"Plugin de Sonarcloud acaba de ser añadido a build.gradle\"\n    cat build.gradle\n  else \n    echo \"Plugin de sonarcloud ya está configurado en build.gradle\"\n  fi\n\n\nelse\n  echo \"no se encontró archivo build.gradle\"\n  exit 1\nfi\n"
+      # - name: Validando existencia de proyecto en SonarCloud
+      #   id: validateProjectOnSonar
+      #   run: |
+      #     #pwd
+      #     #ls -R
+      #     set +e
+      #     echo "Siguiente"
+      #     #curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=glemos-as' -d 'visibility=public'
+      #     #if [ $? -ne 0 ]; then
+      #     #  echo "Proyecto ya existe en Sonarcloud"
+      #     #  echo "project_created=false" >> $GITHUB_ENV
+      #     #else
+      #     #  echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
+      #     #  
+      #     #  echo "Se establece rama main como rama por defecto"
+      #     #  curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
+      #     #  echo "project_created=true" >> $GITHUB_ENV
+      #     #fi
+      #     #set -e
+      - name: Validate or Create SonarCloud Project
+        id: validate-project
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          REPO_NAME: ${{ github.event.repository.name }}
         run: |
-          if [ -f "build.gradle" ]; then
-            echo "Encontró el archivo"
-            echo "Verificando configuracion del plugin sonar"
-            if ! grep -q  'id "org.sonarqube" version "3.3"' build.gradle; then
-              echo "No se encuentra Plugin configurado"
-              sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
-              echo "Plugin de Sonarcloud acaba de ser añadido a build.gradle"
-              cat build.gradle
-            else 
-              echo "Plugin de sonarcloud ya está configurado en build.gradle"
+          echo "Verificando si el proyecto $REPO_NAME existe en SonarCloud..."
+          response=$(curl -s -o /dev/null -w "%{http_code}" -u "$SONAR_TOKEN:" \
+            "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME")
+
+          if [ "$response" -ne 200 ]; then
+            echo "El proyecto no existe. Creándolo en SonarCloud..."
+            create_response=$(curl -s -w "%{http_code}" -o /dev/null -X POST -u "$SONAR_TOKEN:" \
+              "https://sonarcloud.io/api/projects/create" \
+              -d "name=$REPO_NAME" \
+              -d "project=$REPO_NAME" \
+              -d "organization=glemos-as" \
+              -d "visibility=public")
+
+            if [ "$create_response" -ne 201 ]; then
+              echo "¨Proyecto creado exitosamente (HTTP $create_response)."
             fi
 
+            echo "Estableciendo la rama main como predeterminada..."
+            curl -s -f -X POST -u "$SONAR_TOKEN:" \
+              "https://sonarcloud.io/api/project_branches/rename" \
+              -d "name=main" \
+              -d "project=$REPO_NAME"
 
+            echo "project_created=true" >> $GITHUB_ENV
           else
-            echo "no se encontró archivo build.gradle"
-            exit 1
+            echo "El proyecto ya existe en SonarCloud."
+            echo "project_created=false" >> $GITHUB_ENV
           fi
-
-      - name: Validando existencia de proyecto en SonarCloud
-        id: validateProjectOnSonar
-        run: |
-          #pwd
-          #ls -R
-          set +e
-          echo "Siguiente"
-          #curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=devsecopsusach' -d 'visibility=public'
-          #if [ $? -ne 0 ]; then
-          #  echo "Proyecto ya existe en Sonarcloud"
-          #  echo "project_created=false" >> $GITHUB_ENV
-          #else
-          #  echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
-          #  
-          #  echo "Se establece rama main como rama por defecto"
-          #  curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
-          #  echo "project_created=true" >> $GITHUB_ENV
-          #fi
-          #set -e
-      
-      # name: Validate or Create SonarCloud Project
-      # id: validate-project
-      # env:
-      #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      #   REPO_NAME: ${{ github.event.repository.name }}
-      # run: |
-      #   echo "Verificando si el proyecto $REPO_NAME existe en SonarCloud..."
-      #   response=$(curl -s -o /dev/null -w "%{http_code}" -u "$SONAR_TOKEN:" \
-      #     "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME")
-
-      #   if [ "$response" -ne 200 ]; then
-      #     echo "El proyecto no existe. Creándolo en SonarCloud..."
-      #     create_response=$(curl -s -w "%{http_code}" -o /dev/null -X POST -u "$SONAR_TOKEN:" \
-      #       "https://sonarcloud.io/api/projects/create" \
-      #       -d "name=$REPO_NAME" \
-      #       -d "project=$REPO_NAME" \
-      #       -d "organization=devsecopsusach" \
-      #       -d "visibility=public")
-
-      #     if [ "$create_response" -ne 201 ]; then
-      #       echo "¨Proyecto creado exitosamente (HTTP $create_response)."
-      #     fi
-
-      #     echo "Estableciendo la rama main como predeterminada..."
-      #     curl -s -f -X POST -u "$SONAR_TOKEN:" \
-      #       "https://sonarcloud.io/api/project_branches/rename" \
-      #       -d "name=main" \
-      #       -d "project=$REPO_NAME"
-
-      #     echo "project_created=true" >> $GITHUB_ENV
-      #   else
-      #     echo "El proyecto ya existe en SonarCloud."
-      #     echo "project_created=false" >> $GITHUB_ENV
-      #   fi
-
       - name: Enable execution gradlew
-        run: | 
+        run: |
           chmod 777 gradlew
-
       - name: Perform Initial Analysis (if Project Created)
         if: env.project_created == 'true'
         env:
@@ -111,11 +85,10 @@ jobs:
           echo "Realizando análisis inicial en la rama main..."
           ./gradlew sonarqube \
             -Dsonar.projectKey=$REPO_NAME \
-            -Dsonar.organization=devsecopsusach \
+            -Dsonar.organization=glemos-as \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.token=$SONAR_TOKEN \
             -Dsonar.branch.name=main
-
       - name: Perform Branch Analysis
         if: env.project_created == 'false'
         env:
@@ -126,11 +99,10 @@ jobs:
           echo "Realizando análisis en la rama actual: $BRANCH_NAME..."
           ./gradlew sonarqube \
             -Dsonar.projectKey=$REPO_NAME \
-            -Dsonar.organization=devsecopsusach \
+            -Dsonar.organization=glemos-as \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.token=$SONAR_TOKEN \
             -Dsonar.branch.name=${{ github.ref_name }}
-
       - name: Validate Quality Gate
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -157,99 +129,83 @@ jobs:
             echo "El proyecto cumple con el Quality Gate y no tiene vulnerabilidades críticas. Continuando sin problemas."
           fi
 
-  # SCA:
-  #   needs: SAST
-  #   runs-on: ubuntu-24.04
-  #   steps:
-    
-  #   - name: Checkout code
-  #     uses: actions/checkout@v2
-
-  #   - name: Build
-  #     run: |
-  #       if [ -f "build.gradle" ]; then
-  #         echo "Proyecto utiliza archivo build.gradle"
-  #         echo "Se habilita permiso de ejecución de archivo gradlew"
-  #         chmod 777 gradlew
-  #         ./gradlew build
-  #         ls -R
-  #       else 
-  #         echo "Otro tipo de proyecto"
-  #       fi
-    
-  #   - name: Dependency Check
-  #     uses: dependency-check/Dependency-Check_Action@1.1.0
-  #     env:
-  #       JAVA_HOME: /opt/jdk
-  #     id: Depcheck
-  #     with:
-  #       project: '${{ github.event.repository.name }}'
-  #       path: '.'
-  #       format: 'HTML'
-  #       args: >
-  #         --out ./reports
-  #         --failOnCVSS 7
-  #         --enableRetired
-
-  #   - name: Upload Test Result
-  #     uses: actions/upload-artifact@master
-  #     with:
-  #       name: Depcheck Report
-  #       path: ./reports
-    
-  #   - name: Upload JAR
-  #     uses: actions/upload-artifact@master
-  #     with:
-  #       name: JAR
-  #       path: ${{github.workspace}}/build/libs/spring-petclinic-2.6.0.jar
-
-  # DockerBuild:
-  #   needs: SCA
-  #   runs-on: ubuntu-24.04
-  #   steps:
-    
-  #   - name: Checkout code
-  #     uses: actions/checkout@v2
-      
-  #   - name: Docker Login
-  #     uses: docker/login-action@v3.0.0
-  #     with:
-  #       username: ${{ secrets.DOCKER_USER }}
-  #       password: ${{ secrets.DOCKER_PASSWORD }}
-    
-  #   - name: Download JAR
-  #     uses: actions/download-artifact@master
-  #     with:
-  #       name: JAR
-  #       path: ${{github.workspace}}
-
-  #   - name: Docker Build
-  #     run: |
-  #       ls -R
-  #       docker build --tag b4b4y4g4x/cursodevsecops-test:latest .
-
-  #   - name: Push Docker
-  #     run: |
-  #       docker push b4b4y4g4x/cursodevsecops-test:latest
-
-  # DockerScan:
-  #   needs: DockerBuild
-  #   runs-on: ubuntu-24.04
-  #   steps:
-    
-  #   - name: Docker Login
-  #     uses: docker/login-action@v3.0.0
-  #     with:
-  #       username: ${{ secrets.DOCKER_USER }}
-  #       password: ${{ secrets.DOCKER_PASSWORD }}
-    
-  #   - name: Pull Docker
-  #     run: |
-  #       docker pull b4b4y4g4x/cursodevsecops-test:latest
-
-  #   - name: Run Trivy Scan
-  #     uses: aquasecurity/trivy-action@master
-  #     with:
-  #       image-ref: 'b4b4y4g4x/cursodevsecops-test:latest'
-  #       format: 'table'
-
+# SCA:
+#   needs: SAST
+#   runs-on: ubuntu-24.04
+#   steps:
+#   - name: Checkout code
+#     uses: actions/checkout@v2
+#   - name: Build
+#     run: |
+#       if [ -f "build.gradle" ]; then
+#         echo "Proyecto utiliza archivo build.gradle"
+#         echo "Se habilita permiso de ejecución de archivo gradlew"
+#         chmod 777 gradlew
+#         ./gradlew build
+#         ls -R
+#       else 
+#         echo "Otro tipo de proyecto"
+#       fi
+#   - name: Dependency Check
+#     uses: dependency-check/Dependency-Check_Action@1.1.0
+#     env:
+#       JAVA_HOME: /opt/jdk
+#     id: Depcheck
+#     with:
+#       project: '${{ github.event.repository.name }}'
+#       path: '.'
+#       format: 'HTML'
+#       args: >
+#         --out ./reports
+#         --failOnCVSS 7
+#         --enableRetired
+#   - name: Upload Test Result
+#     uses: actions/upload-artifact@master
+#     with:
+#       name: Depcheck Report
+#       path: ./reports
+#   - name: Upload JAR
+#     uses: actions/upload-artifact@master
+#     with:
+#       name: JAR
+#       path: ${{github.workspace}}/build/libs/spring-petclinic-2.6.0.jar
+# DockerBuild:
+#   needs: SCA
+#   runs-on: ubuntu-24.04
+#   steps:
+#   - name: Checkout code
+#     uses: actions/checkout@v2
+#   - name: Docker Login
+#     uses: docker/login-action@v3.0.0
+#     with:
+#       username: ${{ secrets.DOCKER_USER }}
+#       password: ${{ secrets.DOCKER_PASSWORD }}
+#   - name: Download JAR
+#     uses: actions/download-artifact@master
+#     with:
+#       name: JAR
+#       path: ${{github.workspace}}
+#   - name: Docker Build
+#     run: |
+#       ls -R
+#       docker build --tag b4b4y4g4x/cursodevsecops-test:latest .
+#   - name: Push Docker
+#     run: |
+#       docker push b4b4y4g4x/cursodevsecops-test:latest
+# DockerScan:
+#   needs: DockerBuild
+#   runs-on: ubuntu-24.04
+#   steps:
+#   - name: Docker Login
+#     uses: docker/login-action@v3.0.0
+#     with:
+#       username: ${{ secrets.DOCKER_USER }}
+#       password: ${{ secrets.DOCKER_PASSWORD }}
+#   - name: Pull Docker
+#     run: |
+#       docker pull b4b4y4g4x/cursodevsecops-test:latest
+#   - name: Run Trivy Scan
+#     uses: aquasecurity/trivy-action@master
+#     with:
+#       image-ref: 'b4b4y4g4x/cursodevsecops-test:latest'
+#       format: 'table'
